### ISSUE TITLE
运行时报错。。。

### ISSUE THREAD

**Issue by YangJian1994** [GitLqr/LQRImagePicker#3]
java.lang.NullPointerException: Attempt to invoke interface method 'void com.lqr.imagepicker.loader.ImageLoader.displayImage(android.app.Activity, java.lang.String, android.widget.ImageView, int, int)' on a null object reference

**Comment by GitLqr** [comment]
ImageLoader接口由你来实现，出现空指针是你项目问题呀

**Comment by YangJian1994** [comment]
按照你写的这个demo，为什么报错呢。

**Comment by GitLqr** [comment]
按我的文档做，没出过问题，一个程序报错有很多原因，而排查问题的原因要你自己解决的，这是我们程序员的基本能力。每次我使用这个库都没报过错，别人使用也没事，所以很大的可能是因为你本身项目问题导致，请仔细排查。此外，本库制作时并没有适配Android7，可能存在高版本不兼容问题，这跟Android7新特性有关，我手上没有Android7 的手机，所以我现在也没办法做测试，如果是因为Android7新特性导致出现问题，还请见谅。

**Comment by YangJian1994** [comment]
不好意思，今天状态不好，一直去找代码的错误，原来是manifest没添加。原谅我的粗心大意。

**Comment by YangJian1994** [comment]
还有楼主建议很中肯，谢了。

**Comment by GitLqr** [comment]
没事，这种问题也是比较常见，能解决就好，这么晚还打代码真不容易啊，加油。
